repos:
  - repo: https://github.com/ministryofjustice/devsecops-hooks
    rev: v1.5.0
    hooks:
      - id: baseline
        env:
          STAGE_MODE: "false"
  - repo: local
    hooks:
      - id: rubocop
        name: rubocop
        entry: bundle exec rubocop --force-exclusion
        language: system
      - id: erblint
        name: erblint
        entry: bundle exec erb_lint --lint-all
        language: system
