feature_flags:
  developer_tools:
    local: true
    staging: true
    production: false
  u18_means_passport:
    local: true
    staging: true
    production: true
  u18_ioj_passport:
    local: true
    staging: true
    production: true
  offence_ioj_slipstream:
    local: true
    staging: true
    production: true
  means_journey:
    local: true
    staging: true
    production: true
  employment_journey:
    local: true
    staging: true
    production: true
  self_employed_journey:
    local: true
    staging: true
    production: true
  evidence_validation:
    local: true
    staging: true
    production: true
  cifc_journey:
    local: true
    staging: true
    production: true
  arc:
    local: true
    staging: true
    production: true
  other_charges:
    local: true
    staging: true
    production: true
  search:
    local: true
    staging: false
    production: false

# NOTE: consider if the setting you are adding here
# should belong in the k8s `config_map`, which is
# usually the case if it varies per environment.
settings:
  portal_url: https://portal.legalservices.gov.uk
  eforms_url: https://portal.legalservices.gov.uk/oamfed/idp/initiatesso?providerid=eForms
  portal_terms_url: https://www.gov.uk/government/publications/laa-online-portal-help-and-information#attachment_6742318
  laa_privacy_notice_url: https://www.gov.uk/government/publications/laa-online-portal-help-and-information#attachment_6742320
  feedback_survey_url: https://eu.surveymonkey.com/r/feedbackapplyforcriminallegalaid
  onboarding_email: LAAapplyonboarding@justice.gov.uk
  support_email: online-support@justice.gov.uk
  case_enquiries_tel: 0300 200 2020
