name: ZAP Full DAST Scan
permissions: {}
on:
  schedule:
    - cron: "0 8 * * 5" # 8 AM every Friday
  workflow_dispatch:

jobs:
  zap_scan_staging:
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Full Scan - Staging
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: "https://staging.apply-for-criminal-legal-aid.service.justice.gov.uk/"
          fail_action: true
          allow_issue_writing: false
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v6.0.0
        with:
          name: zap-full-report-staging
          path: report_html.html
