name: ZAP Full DAST Scan
permissions:
  issues: write

on:
  schedule:
    - cron: "0 8 * * *" # 8 AM every day
  workflow_dispatch:

jobs:
  zap_scan_staging:
    runs-on: ubuntu-latest

    steps:
      - name: ZAP Full Scan - Staging
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: "https://staging.apply-for-criminal-legal-aid.service.justice.gov.uk/"
          fail_action: false
          allow_issue_writing: true
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v7
        with:
          path: report_html.html
          archive: false
